title: Tiago Coviello # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Sou formado em Análise e Desenvolvimento de Sistemas pela FATEC-SP e atualmente curso pós graduação em Ciência de Dados e Big Data Analytics.
  <br/>
  Tenho interesse em atuar e adquirir experiência na área de desenvolvimento de sistemas e dados.
  <br><br>
  <a href="https://www.linkedin.com/in/0428b0227/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
